version: '3'

services:
   yundocs:
     image: ghost:latest
     ports:
        - 127.0.0.1:2368:2368
     volumes:
        - ./data:/var/lib/ghost/content
        # If you need custom config, uncomment below
        #- ./config.production.json:/var/lib/ghost/config.production.json
     environment:
        - url=https://ghost.nova.moe
     restart: always

