version: "3"
services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_DOMAIN=internal.example.com
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_ROOT_URL=https://internal.example.com/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
